### ISSUE TITLE
Pops up everytime

### ISSUE THREAD

**Issue by HelloDev18** [takecian/SwiftRater#19]
Hi, the dialog pops up from the first launch even if debug is false and in real device.
Swift 4. iOS: 11.3. XCode 10.1
My Settings:
SwiftRater.daysUntilPrompt = 3
        SwiftRater.usesUntilPrompt = 1
        SwiftRater.significantUsesUntilPrompt = 2
        SwiftRater.daysBeforeReminding = 2

**Comment by takecian** [comment]
Hello, which version are you using?
What api did you call for showing popup?

**Comment by HelloDev18** [comment]
thanks for the quick reply, I use the latest version of your library
 SwiftRater.check()

**Comment by takecian** [comment]
Ah, I guess this is because you have set `usesUntilPrompt` 1.

>Shows review request if users launch more than usesUntilPrompt times.

I documented above about `usesUntilPrompt`, but I checked code now this document is wrong,

Currently my library works "Shows review request if users launch more than `equal` usesUntilPrompt times."
Could you try setting `usesUntilPrompt` is 2?

Anyway I will fix code to follow document.

**Comment by takecian** [comment]
I updated, `1.3.1`.
This works according to document,
>Shows review request if users launch more than usesUntilPrompt times.

**Comment by takecian** [comment]
If you have question more, please reopen.
